name: Full Integration Tests

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Deno
      uses: denoland/setup-deno@v1
      with:
        deno-version: v1.40.0
        
    - name: Setup Foundry
      uses: foundry-rs/foundry-toolchain@v1
      with:
        version: nightly
        
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
        cache-dependency-path: modules/subgraph/package-lock.json
        
    - name: Install subgraph dependencies
      run: |
        cd modules/subgraph
        npm install
        
    - name: Install Docker Compose
      run: |
        sudo curl -L "https://github.com/docker/compose/releases/latest/download/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
        sudo chmod +x /usr/local/bin/docker-compose
        
    - name: Build contract
      run: forge build
      
    - name: Run Foundry tests
      run: forge test
      
    - name: Run full integration test
      run: deno task test:full
        